### ISSUE TITLE
Null reference exception on opening file

### ISSUE THREAD

**Issue by SylwesterZarebski** [KhaosCoders/VSCodeBlockEndTag#20]
Sometimes when opening file i got exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
  at CodeBlockEndTag.CBETagger.Dispose(Boolean disposing)
  at CodeBlockEndTag.CBETagger.Dispose()
  at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<>c__DisplayClass46_0.<UnregisterTagger>b__1()
  at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

Besides of that extension works.

VS 2017 - 15.9.13

**Comment by Khaos66** [comment]
Yes, I was getting the same today and was planing on fixing it ASAP ;) Thanks for reporting

**Comment by Khaos66** [comment]
Fixed. Update should ne ready soon ;)
